"""primeiro migrate

Revision ID: 761ba789da41
Revises: 
Create Date: 2024-05-22 17:02:18.386307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761ba789da41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registrar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registrar')
    # ### end Alembic commands ###
